{% set version = "4.0.0" %}

package:
  name: mpfr
  version: {{ version }}

source:
  fn: mpfr-{{ version }}.tar.bz2
  url: http://ftp.gnu.org/gnu/mpfr/mpfr-{{ version }}.tar.gz
  sha256: f65bb6c295c8716ea06adc3c2aab2f0e6e410464ba5a86bfd10c6259e64876a2

build:
  number: 0
  features:
    - vc14            # [win]
  msvc_compiler: 14.0

requirements:
  build:
    - toolchain
    - m4              # [unix]
    - libtool         # [unix]
    - gmp             # [unix]
    - vc 14           # [win]
    - mpir            # [win]
  run:
    - gmp             # [unix]
    - mpir            # [win]
    - vc 14           # [win]

test:
  commands:
    - if not exist %LIBRARY_INC%\\mpfr.h exit 1                # [win]
    - if not exist %LIBRARY_LIB%\\mpfr.lib exit 1              # [win]
    - if not exist %LIBRARY_BIN%\\mpfr.dll exit 1              # [win]
    - if not exist %LIBRARY_LIB%\\mpfr_static.lib exit 1       # [win]
    - test -f ${PREFIX}/lib/libmpfr.a                          # [unix]
    - test -f ${PREFIX}/lib/libmpfr.dylib                      # [osx]
    - test -f ${PREFIX}/lib/libmpfr.so                         # [linux]

about:
  home: http://www.mpfr.org/
  license: LGPL 3
  license_file: {{ SRC_DIR }}/COPYING.LESSER
  summary: The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
