{% set version = "3.1.4" %}
{% set commit = "71f5b2d5b68192424fce6bd1768a889710fc5933" %}

package:
  name: mpfr
  version: {{ version }}

source:
  fn: mpfr-{{ commit }}-{{ version }}.zip                                   # [unix]
  url: http://ftp.gnu.org/gnu/mpfr/mpfr-{{ version }}.tar.gz                # [unix]
  md5: 482ab3c120ffc959f631b4ba9ec59a46                                     # [unix]
  fn: mpfr-{{ commit }}-{{ version }}.zip                                   # [win]
  url: https://github.com/BrianGladman/mpfr/archive/{{ commit }}.zip        # [win]
  md5: 9d84b0d1ac32244e837d1b220b0ceb73                                     # [win]

build:
  number: 3
  features:
    - vc14            # [win]
  msvc_compiler: 14.0

requirements:
  build:
    - toolchain
    - m4              # [unix]
    - libtool         # [unix]
    - gmp             # [unix]
    - vc 14           # [win]
    - mpir            # [win]
  run:
    - gmp             # [unix]
    - mpir            # [win]
    - vc 14           # [win]

test:
  commands:
    - if not exist %LIBRARY_INC%\\mpfr.h exit 1                # [win]
    - if not exist %LIBRARY_LIB%\\mpfr.lib exit 1              # [win]
    - if not exist %LIBRARY_BIN%\\mpfr.dll exit 1              # [win]
    - if not exist %LIBRARY_LIB%\\mpfr_static.lib exit 1       # [win]
    - test -f ${PREFIX}/lib/libmpfr.a                          # [unix]
    - test -f ${PREFIX}/lib/libmpfr.dylib                      # [osx]
    - test -f ${PREFIX}/lib/libmpfr.so                         # [linux]

about:
  home: http://www.mpfr.org/
  license: LGPL 3
  license_file: COPYING.LESSER
  summary: The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
