{% set version = "3.1.4" %}

package:
  name: mpfr
  version: {{ version }}

source:
  fn: mpfr-{{ version }}.tar.bz2                              # [unix]
  url: http://ftp.gnu.org/gnu/mpfr/mpfr-{{ version }}.tar.gz  # [unix]
  md5: 482ab3c120ffc959f631b4ba9ec59a46                       # [unix]
  git_url: https://github.com/BrianGladman/mpfr               # [win]
  git_rev: 30e80d67e4c1e287ae2f10110ec03b5630596f4a           # [win]

build:
  number: 1
  skip: true          # [win and not py35]
  features:
    - vc14            # [win and py35]

requirements:
  build:
    - m4              # [unix]
    - libtool         # [unix]
    - gmp             # [unix]
    - python          # [win]
    - mpir            # [win]
  run:
    - gmp             # [unix]
    - mpir            # [win]

test:
  commands: 
    - if not exist %LIBRARY_INC%\\mpfr.h exit 1                # [win]
    - if not exist %LIBRARY_LIB%\\mpfr.lib exit 1              # [win]
    - if not exist %LIBRARY_BIN%\\mpfr.dll exit 1              # [win]
    - if not exist %LIBRARY_LIB%\\mpfr_static.lib exit 1       # [win]
    - test -f ${PREFIX}/lib/libmpfr.a                          # [unix]
    - test -f ${PREFIX}/lib/libmpfr.dylib                      # [osx]
    - test -f ${PREFIX}/lib/libmpfr.so                         # [linux]

about:
  home: http://www.mpfr.org/
  license: LGPL 3
  summary: The MPFR library is a C library for multiple-precision floating-point computations with correct rounding.

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
